server:
  port: 8000
  servlet:
    context-path: /@pom.artifactId@
spring:
  application:
    name: @pom.artifactId@
  #mysql数据源
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?search_path=web
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug