server:
  port: 8000
  servlet:
    context-path: /@pom.artifactId@
spring:
  application:
    name: @pom.artifactId@
  datasource:
    url: jdbc:mysql://localhost:3306/WEB?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456