server:
  port: 8000
  servlet:
    context-path: /@pom.artifactId@
spring:
  application:
    name: @pom.artifactId@
  #redis 数据源
  redis:
    database: 0
    port: 6379
    host: localhost
  #mysql数据源
  datasource:
    url: jdbc:mysql://localhost:3306/WEB?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.cloud.auth.entity
  mapper-locations: classpath:mapper/*xml
  configuration:
    map-underscore-to-camel-case: true