server:
  port: 8081
  servlet:
    context-path: /@pom.artifactId@
spring:
  application:
    name: @pom.artifactId@
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: false
