server:
  port: 7999
  servlet:
    context-path: /config
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuin23/web
          search-paths: config

