server:
  port: 8082
  servlet:
    context-path: /@pom.artifactId@

spring:
  application:
    name: @pom.artifactId@
  #redis 数据源
  redis:
    database: 0
    port: 6379
    host: localhost
  mail:
    host: smtp.qq.com
    username: 1486204732@qq.com #邮箱
    password: afrgchyablxhjcba #授权码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
eureka:
  client:
    register-with-eureka: true
