server:
  port: 8000
  servlet:
    context-path: /@pom.artifactId@
spring:
  application:
    name: @pom.artifactId@
  #redis 数据源
  redis:
    database: 0
    port: 6379
    host: localhost
  #postgres数据源
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

#mybatis配置
mybatis:
  type-aliases-package: com.cloud.auth.entity
  mapper-locations: classpath:mapper/*xml
  configuration:
    map-underscore-to-camel-case: true

#日志配置
logging:
  level:
    com:
      cloud:
        auth:
          mapper: debug
