server:
  port: 7999
  servlet:
    context-path: /@pom.artifactId@
spring:
  application:
    name: @pom.artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuin23/web
          search-paths: config
