server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: operator
          uri: lb://web-operator
          predicates:
            - Path=/web-operator/**
#          filters:
#            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
